kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-viewer-role-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-access
subjects:
  - kind: Group
    namespace: web
    name: groupObjectId
