kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-only-access
  namespace: roleNamespace
rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
