kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-viewer-role-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-access
subjects:
  - kind: Group
    namespace: api
    name: groupObjectId
