version: '3'
services:
  poi:
    build:
      context: ../src/poi
      dockerfile: ../../dockerfiles/Dockerfile_3
    image: "${REGISTRY}/poi:1.0"

  trips:
    build:
      context: ../src/trips
      dockerfile: ../../dockerfiles/Dockerfile_4
    image: "${REGISTRY}/trips:1.0"
  
  user-java:
    build:
      context: ../src/user-java
      dockerfile: ../../dockerfiles/Dockerfile_0
    image: "${REGISTRY}/user-java:1.0"
  
  userprofile:
    build:
      context: ../src/userprofile
      dockerfile: ../../dockerfiles/Dockerfile_2
    image: "${REGISTRY}/userprofile:1.0"

  tripviewer:
    build:
      context: ../src/tripviewer
      dockerfile: ../../dockerfiles/Dockerfile_1
    image: "${REGISTRY}/tripviewer:1.0"