version: "3"
services:
  poi:
    build:
      context: ../src/poi
      dockerfile: ../../dockerfiles/Dockerfile_3
    image: tripinsights/poi:1.0
    ports:
      - "8080:8080"
    environment:
      SQL_USER: "sa"
      SQL_PASSWORD: "Your_password123!"
      SQL_SERVER: "sql-db"
      SQL_DBNAME: "mydrivingDB"
      WEB_PORT: "8080"
      ASPNETCORE_ENVIRONMENT: "Local"
      ASPNETCORE_URLS: "http://+:8080"

  sql-db:
    container_name: sql-db
    build:
      context: ../mssql-db/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"

  data-load:
    container_name: data-load
    image: "openhack/data-load:v1"
    depends_on: 
      - sql-db
    environment:
      SQLFQDN: "sql-db"
      SQLUSER: "sa"
      SQLPASS: "Your_password123!"
      SQLDB: "mydrivingDB"
    entrypoint: [
            "/bin/bash",
            "-c",
            "sleep 25s ; ./sql_data_init.sh -s sql-db -u sa -p Your_password123! -d mydrivingDB"
        ]
