apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    keyvaultName: "openhacklab4kv"                # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: sql-server
          objectAlias: SQL_SERVER     
          objectType: secret
          objectVersion: ""
        - |
          objectName: sql-password
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: sql-user
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
    tenantId: "21461264-1936-4030-8909-bd9037302654"                       # the tenant ID of the KeyVault